import fs from "node:fs";
import path from "node:path";
import type { Inference, RunPlan, PlanStep } from "./types.js";

const SERVICE_IMAGES: Record<string, { image: string; port: number; env: Record<string, string> }> = {
  postgres: { image: "postgres:16-alpine", port: 5432, env: { POSTGRES_USER: "bootproof", POSTGRES_PASSWORD: "bootproof", POSTGRES_DB: "app" } },
  mysql: { image: "mysql:8", port: 3306, env: { MYSQL_ROOT_PASSWORD: "bootproof", MYSQL_DATABASE: "app" } },
  redis: { image: "redis:7-alpine", port: 6379, env: {} },
  mongodb: { image: "mongo:7", port: 27017, env: {} },
};

export const REPAIRED_GENERATED_COMPOSE_MARKER = "# BootProof verified repair: remap-conflicting-service-port";

export function repoComposeRepairFile(repoComposeFile: string): string {
  const directory = path.posix.dirname(repoComposeFile.replace(/\\/g, "/"));
  const file = "docker-compose.bootproof.override.yml";
  return directory === "." ? file : path.posix.join(directory, file);
}

export function composeFileFor(inf: Inference): string | null {
  if (inf.repoComposeFile) return null;
  if (!inf.services.length) return null;
  const existingPath = path.join(inf.repoPath, "docker-compose.bootproof.yml");
  if (fs.existsSync(existingPath)) {
    const existing = fs.readFileSync(existingPath, "utf8");
    if (existing.includes(REPAIRED_GENERATED_COMPOSE_MARKER)) return existing;
  }
  const lines = ["# Generated by bootproof — review before use. Standard compose; no bootproof runtime required.", "services:"];
  for (const s of inf.services) {
    const spec = SERVICE_IMAGES[s.kind];
    lines.push(`  ${s.kind}:`, `    image: ${spec.image}`, `    ports:`, `      - "${spec.port}:${spec.port}"`);
    const envKeys = Object.entries(spec.env);
    if (envKeys.length) {
      lines.push("    environment:");
      for (const [k, v] of envKeys) lines.push(`      ${k}: ${v}`);
    }
  }
  return lines.join("\n") + "\n";
}

export function envExampleFor(inf: Inference): string | null {
  if (!inf.requiredEnv.length) return null;
  const lines = [
    "# Generated by bootproof from .env.example — local-only suggested values.",
    "# Bootproof NEVER writes .env/.env.local; copy values yourself if they look right.",
  ];
  for (const key of inf.requiredEnv) {
    if (inf.envWithoutSafeDefault.includes(key)) {
      lines.push(`# ${key}= (secret with no safe local default — bootproof will not invent one)`);
    } else if (/^DATABASE_URL$/.test(key) && inf.services.some(s => s.kind === "postgres")) {
      lines.push(`${key}=postgresql://bootproof:bootproof@localhost:5432/app`);
    } else if (/^PORT$/.test(key)) {
      lines.push(`${key}=${inf.port}`);
    } else {
      lines.push(`${key}=`);
    }
  }
  return lines.join("\n") + "\n";
}

export function buildPlan(inf: Inference, provider: "docker" | "local"): RunPlan {
  const steps: PlanStep[] = [];
  const runsSourceComposeApplication =
    provider === "docker" &&
    Boolean(inf.repoComposeFile) &&
    inf.composeHealthCandidates.length > 0;
  if (provider === "docker" && inf.repoComposeFile) {
    const repairedCompose = repoComposeRepairFile(inf.repoComposeFile);
    const usesRepairedCopy = fs.existsSync(path.join(inf.repoPath, repairedCompose));
    steps.push({
      id: "services",
      kind: "service",
      command: `docker compose -f ${usesRepairedCopy ? repairedCompose : inf.repoComposeFile} up -d`,
      description: usesRepairedCopy
        ? "use the BootProof repaired copy of the repository Compose file"
        : "defer to the repository's own compose file",
      required: true,
    });
  } else if (inf.services.length && provider === "docker") {
    steps.push({ id: "services", kind: "service", command: "docker compose -f docker-compose.bootproof.yml up -d", description: `start ${inf.services.map(s => s.kind).join(", ")} in containers`, required: true });
  }
  if (!runsSourceComposeApplication) {
    for (const preparation of inf.preparationCommands) {
      steps.push({
        id: preparation.id,
        kind: preparation.kind,
        command: preparation.command,
        description: `${preparation.description} (${preparation.source})`,
        required: true,
      });
    }
    if (inf.appCommand) {
      steps.push({ id: "start-app", kind: "start-app", command: inf.appCommand, description: `start app (${inf.appCommandSource})`, required: true });
    }
  }
  const healthCandidates = runsSourceComposeApplication
    ? [...inf.composeHealthCandidates]
    : [...inf.healthCandidates];
  const healthUrl = healthCandidates[0] ?? "";
  if (inf.isApplication && healthUrl) {
    steps.push({ id: "health", kind: "health", description: `poll ${healthUrl} for an HTTP response`, required: true });
  }
  return {
    provider,
    steps,
    healthUrl,
    healthCandidates,
    observedPort: inf.observedPort,
    healthCandidateSource: inf.healthCandidateSource,
    generatedFiles: [
      ...(composeFileFor(inf) ? [{ path: "docker-compose.bootproof.yml", purpose: "service containers" }] : []),
      ...(envExampleFor(inf) ? [{ path: ".env.bootproof.example", purpose: "suggested local env values (never auto-applied)" }] : []),
    ],
  };
}

const PROTECTED_ENV = [".env", ".env.local", ".env.development", ".env.production"];

export function writePlanFiles(inf: Inference, repo: string): string[] {
  const written: string[] = [];
  const compose = composeFileFor(inf);
  if (compose) { fs.writeFileSync(path.join(repo, "docker-compose.bootproof.yml"), compose); written.push("docker-compose.bootproof.yml"); }
  const envEx = envExampleFor(inf);
  if (envEx) { fs.writeFileSync(path.join(repo, ".env.bootproof.example"), envEx); written.push(".env.bootproof.example"); }
  for (const p of PROTECTED_ENV) {
    if (written.includes(p)) throw new Error(`honesty contract violation: attempted to write ${p}`);
  }
  return written;
}

export { PROTECTED_ENV };
